
App.Player = Em.Object.extend({
    whitelisted: null,
    firstPlayed: null,
    worldInfo: null,
    op: null,
    location: null,
    exhaustion: null,
    lastPlayed: null,
    sleeping: null,
    health: null,
    banned: null,
    ip: null,
    gameMode: null,
    inVehicle: null,
    level: null,
    inventory: null,
    name: null,
    foodLevel: null,
    experience: null,
    itemInHand: null,
    sneeking: null,
    world: null,
    sprinting: null,
    online: false,
    face: null
});
